#!/bin/sh

# auto-xflux
# inputless xflux daemon that geocodes based on your external IP address

# Copyright 2014 James An

# THIS PROGRAM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

K=''

while getopts 'k:' opt; do
  case "${opt}" in
    k) if ! [[ "$OPTARG" =~ ([2-6][0-9][0-9][0-9]) ]] ; 
      then exec >&2; echo "error: not a valid temperature value"; exit 1
      fi 
     
      K=$OPTARG 
  esac
done

LOCATION=$(curl --silent ipinfo.io | grep '"loc":' | cut --delimiter='"' --fields=4)
LAT=`echo $LOCATION | cut -f 1 -d ","`
LNG=`echo $LOCATION | cut -f 2 -d ","`

# start xflux in daemon mode (forking)
/usr/bin/xflux -l $LAT -g $LNG -k $K
